services:
  vert:
    container_name: vert
    image: ghcr.io/vert-sh/vert:sha-38ec057
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.routers.vert.entryPoints: websecure
      traefik.http.services.vert.loadbalancer.server.port: 80
      traefik.http.routers.vert.rule: Host(`convert.hoebergen.net`)
      traefik.http.routers.vert.middlewares: localAccess@file

networks:
  default:
    name: frontend
    external: true