server:
  # Hostname where the application can be reached at externally
  hostname: "authproxy.lab-vps-02.hoebergen.net"

cookies:
  # Domain for setting cookies
  domain: "hoebergen.net"

portals:
  - name: "mediastack"
    providers:
    - pocketID:
        name: "my-pocketid-auth"
        displayName: "Pocket ID"
        endpoint: "https://auth.hoebergen.net"
        clientID: "2e30a388-fc52-41e4-915d-da7507bcce68"
        clientSecret: "ZBiebA6jnPOpu3hpImoEZ1TAWaWLPnZB"