server:
  # Hostname where the application can be reached at externally
  hostname: "authproxy.lab-vps-01.hoebergen.net"

cookies:
  # Domain for setting cookies
  domain: "hoebergen.net"

portals:
  - name: "default"
    providers:
      - pocketID:
        name: "my-pocketid-auth"
        displayName: "Pocket ID"
        endpoint: "https://auth.hoebergen.net"
        clientID: "25ae4a85-5a2e-48d9-a224-03e8d374a20c"
        clientSecret: "QlJVC0t8U1DcBNtaflsQ5Nozw0KaZHuQ"