server:
  # Hostname where the application can be reached at externally
  hostname: "authproxy.lab-vps-01.hoebergen.net"

cookies:
  # Domain for setting cookies
  domain: "hoebergen.net"

portals:
  - name: "main"
    providers:
      - pocketID:
        #name: "my-pocketid-auth"
        #displayName: "Pocket ID"
        endpoint: "https://auth.hoebergen.net"
        clientID: "your-client-id"
        clientSecret: "your-client-secret"